# Generated by Django 4.1 on 2024-07-03 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 1, 37, 50, 960759, tzinfo=datetime.timezone.utc)),
        ),
    ]
