# Generated by Django 4.1 on 2024-07-06 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 7, 32, 37, 631930, tzinfo=datetime.timezone.utc)),
        ),
    ]
