name: terrarium-auto-run

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/Checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
      - name: Pull from Staging Branch to Local Server
        run: | 
            cd /Users/mycutemacbook/Project/Terrarium
            git pull origin staging
